### ISSUE TITLE
sd nix wrapper

### ISSUE THREAD

**Issue by gerardbosch** [ianthehenry/dotfiles#3]
Hi again =)

Have you published somewhere the implementation for `sd nix sync`?
I found that in [your blog](https://ianthehenry.com/posts/sd-my-script-directory/) but can't actually find the scripts or the code (neither in the blog nor this dotfiles repo) - EDIT: I found the [info](https://ianthehenry.com/posts/how-to-learn-nix/switching-from-homebrew-to-nix/) and [diff](obsessive.granddad7.exes.happiness) in the blog, but not `sync`.

I guess you've decided not publish (or not yet) your `~/sd` scripts in this dotfiles repo.

I'd also like to simplify Nix CLI a little for the most used commands and I liked the idea of `sync`/`diff` and others you implemented.

Thx!

**Comment by ianthehenry** [comment]
I had not, but now I have:

https://github.com/ianthehenry/sd-nix

Sync is just the one-liner `nix-env -irf ~/dotfiles/user.nix`, which is explained [in this blog post](https://ianthehenry.com/posts/how-to-learn-nix/declarative-user-environment/), but it didn't get a big callout the way that `diff` did.

**Comment by gerardbosch** [comment]
Thank you!!
